<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AirportsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        /**
         * @todo
         * How About storing the airports in json file and loop thought them here?...
         * as the data will be huge.. i think will be easier for us to manage it as json
         */
//        $airports = new \Symfony\Component\Translation\Loader\JsonFileLoader('...json path');
//
//        foreach($airports  as $airport){
//            \App\Models\Airport::create($airport);
//        }

        DB::table('airports')->insert(['name' => 'Andorra la Vella Airport (ALV)', 'iata' => 'ALV', 'latitude' => 42.5004997, 'longitude' => 1.51712, 'timezone' => 'Europe/Andorra', 'runways' => 0, 'city' => 'Andorra La Vella', 'country' => 'Andorra (AD)']);
        DB::table('airports')->insert(['name' => 'Andulo Airport (ANL)', 'iata' => 'ANL', 'latitude' => -11.4722996, 'longitude' => 16.7108994, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => '', 'country' => '']);
        DB::table('airports')->insert(['name' => 'Cangamba Airport (CNZ)', 'iata' => 'CNZ', 'latitude' => -13.7105999, 'longitude' => 19.8610992, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Cangamba', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Dirico Airport (DRC)', 'iata' => 'DRC', 'latitude' => -17.9819241, 'longitude' => 20.7680607, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Dirico', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Lumbala Airport (GGC)', 'iata' => 'GGC', 'latitude' => -12.6398773, 'longitude' => 22.5868206, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Lumbala', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Jamba Airport (JMB)', 'iata' => 'JMB', 'latitude' => -14.6981926, 'longitude' => 16.0701485, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Jamba', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Capanda Airport (KNP)', 'iata' => 'KNP', 'latitude' => -9.7693701, 'longitude' => 15.4553194, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Capanda', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Ndalatandos Airport (NDF)', 'iata' => 'NDF', 'latitude' => -9.2751884, 'longitude' => 14.9772425, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Ndalatandos', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Ambriz Airport (AZZ)', 'iata' => 'AZZ', 'latitude' => -7.8622198, 'longitude' => 13.1161003, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Ambriz', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Benguela Airport (BUG)', 'iata' => 'BUG', 'latitude' => -12.6090002, 'longitude' => 13.4036999, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Benguela', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Cabinda Airport (CAB)', 'iata' => 'CAB', 'latitude' => -5.5969901, 'longitude' => 12.1884003, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Cabinda', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Cafunfo Airport (CFF)', 'iata' => 'CFF', 'latitude' => -8.7836103, 'longitude' => 17.9897003, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Cafunfo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Chitato Airport (PGI)', 'iata' => 'PGI', 'latitude' => -7.3588901, 'longitude' => 20.8047009, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Chitato', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Catumbela Airport (CBT)', 'iata' => 'CBT', 'latitude' => -12.4792004, 'longitude' => 13.4869003, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Catumbela', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Cuito Cuanavale Airport (CTI)', 'iata' => 'CTI', 'latitude' => -15.1603003, 'longitude' => 19.1560993, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Cuito Cuanavale', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Cazombo Airport (CAV)', 'iata' => 'CAV', 'latitude' => -11.8930998, 'longitude' => 22.9164009, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Cazombo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Dundo Airport (DUE)', 'iata' => 'DUE', 'latitude' => -7.4008899, 'longitude' => 20.8185005, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Chitato', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Ngjiva Pereira Airport (VPE)', 'iata' => 'VPE', 'latitude' => -17.0435009, 'longitude' => 15.6837997, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Ngiva', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Nova Lisboa Airport (NOV)', 'iata' => 'NOV', 'latitude' => -12.8088999, 'longitude' => 15.7605, 'timezone' => 'Africa/Luanda', 'runways' => 2, 'city' => 'Huambo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Kuito Airport (SVP)', 'iata' => 'SVP', 'latitude' => -12.4046001, 'longitude' => 16.9473991, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Kuito', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Quatro De Fevereiro Airport (LAD)', 'iata' => 'LAD', 'latitude' => -8.8583698, 'longitude' => 13.2312002, 'timezone' => 'Africa/Luanda', 'runways' => 2, 'city' => 'Luanda', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Malanje Airport (MEG)', 'iata' => 'MEG', 'latitude' => -9.5250902, 'longitude' => 16.3124008, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Malanje', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Menongue Airport (SPP)', 'iata' => 'SPP', 'latitude' => -14.6576004, 'longitude' => 17.7198009, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Menongue', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Namibe Airport (MSZ)', 'iata' => 'MSZ', 'latitude' => -15.2612, 'longitude' => 12.1468, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Namibe', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Negage Airport (GXG)', 'iata' => 'GXG', 'latitude' => -7.7545099, 'longitude' => 15.2876997, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Negage', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Porto Amboim Airport (PBN)', 'iata' => 'PBN', 'latitude' => -10.7220001, 'longitude' => 13.7655001, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Port Amboim', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Saurimo Airport (VHC)', 'iata' => 'VHC', 'latitude' => -9.6890697, 'longitude' => 20.4319, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Saurimo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Soyo Airport (SZA)', 'iata' => 'SZA', 'latitude' => -6.1410899, 'longitude' => 12.3718004, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Soyo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Sumbe Airport (NDD)', 'iata' => 'NDD', 'latitude' => -11.1679001, 'longitude' => 13.8474998, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Sumbe', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Luau Airport (UAL)', 'iata' => 'UAL', 'latitude' => -10.7158003, 'longitude' => 22.2311001, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Luau', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Lubango Airport (SDD)', 'iata' => 'SDD', 'latitude' => -14.9246998, 'longitude' => 13.5749998, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Lubango', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Luena Airport (LUO)', 'iata' => 'LUO', 'latitude' => -11.7680998, 'longitude' => 19.8976994, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Luena', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Uige Airport (UGO)', 'iata' => 'UGO', 'latitude' => -7.6030698, 'longitude' => 15.0277996, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Uige', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Waco Kungo Airport (CEO)', 'iata' => 'CEO', 'latitude' => -11.4264002, 'longitude' => 15.1014004, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Waco Kungo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Xangongo Airport (XGN)', 'iata' => 'XGN', 'latitude' => -16.7553997, 'longitude' => 14.9652996, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Xangongo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Lucapa Airport (LBZ)', 'iata' => 'LBZ', 'latitude' => -8.4457273, 'longitude' => 20.7320862, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Lucapa', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Luzamba Airport (LZM)', 'iata' => 'LZM', 'latitude' => -4.9666667, 'longitude' => 23.45, 'timezone' => 'Africa/Bujumbura', 'runways' => 0, 'city' => 'Luzamba', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Ngiva Airport (NGV)', 'iata' => 'NGV', 'latitude' => 23.0761111, 'longitude' => 34.3744444, 'timezone' => 'Asia/Gaza', 'runways' => 0, 'city' => 'Ngiva', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Saurimo NorthAirport', 'iata' => '', 'latitude' => -9.4334297, 'longitude' => 20.3118, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Saurimo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'NankovaAirport', 'iata' => '', 'latitude' => -16.3963699, 'longitude' => 18.9787636, 'timezone' => 'Africa/Windhoek', 'runways' => 0, 'city' => '', 'country' => '']);
        DB::table('airports')->insert(['name' => 'RitoAirport', 'iata' => '', 'latitude' => -16.6893921, 'longitude' => 19.0837669, 'timezone' => 'Africa/Windhoek', 'runways' => 0, 'city' => '', 'country' => '']);
        DB::table('airports')->insert(['name' => 'CoembaAirport', 'iata' => '', 'latitude' => -12.1437044, 'longitude' => 18.0853634, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => '', 'country' => '']);
        DB::table('airports')->insert(['name' => 'Cahama Airport (FN17)', 'iata' => '', 'latitude' => -16.2383995, 'longitude' => 14.3260002, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Cahama', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Matala Airport (FN18)', 'iata' => '', 'latitude' => -14.7275, 'longitude' => 15.0139999, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Matala', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Cabo Ledo Airport (FN19)', 'iata' => '', 'latitude' => -9.6530504, 'longitude' => 13.2606001, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Cabo Ledo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Mbanza Congo Airport (SSY)', 'iata' => 'SSY', 'latitude' => -6.2698998, 'longitude' => 14.2469997, 'timezone' => 'Africa/Kinshasa', 'runways' => 1, 'city' => 'Mbanza Congo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Camembe Airport (FNCB);', 'iata' => '', 'latitude' => -8.1330004, 'longitude' => 14.5, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Camembe', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Cacolo Airport (FNCC);', 'iata' => '', 'latitude' => -10.283, 'longitude' => 19.2670002, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Cacolo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Camabatela Airport (FNCM);', 'iata' => '', 'latitude' => -8.217, 'longitude' => 15.3669996, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Camabatela', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Camaxilo Airport (CXM)', 'iata' => 'CXM', 'latitude' => -8.3736095, 'longitude' => 18.9235992, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Camaxilo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Damba Airport (FNDB);', 'iata' => '', 'latitude' => -6.9000001, 'longitude' => 15.1330004, 'timezone' => 'Africa/Kinshasa', 'runways' => 0, 'city' => 'Damba', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Lobito Airport (FNLB);', 'iata' => '', 'latitude' => -12.3711996, 'longitude' => 13.5366001, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Lobito', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Maquela do Zombo Airport (FNMQ);', 'iata' => '', 'latitude' => -6.0302801, 'longitude' => 15.1368999, 'timezone' => 'Africa/Kinshasa', 'runways' => 0, 'city' => 'Maquela do Zombo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Sanza Pombo Airport (FNPB);', 'iata' => '', 'latitude' => -7.3000002, 'longitude' => 15.9329996, 'timezone' => 'Africa/Kinshasa', 'runways' => 0, 'city' => 'Sanza Pombo', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Toto Airport (FNTO);', 'iata' => '', 'latitude' => -7.14639, 'longitude' => 14.2486, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Toto', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'N\'zeto Airport (ARZ)', 'iata' => 'ARZ', 'latitude' => -7.2594399, 'longitude' => 12.8631001, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'N\'zeto', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Nzagi Airport (FNZG);', 'iata' => '', 'latitude' => -7.7169399, 'longitude' => 21.3582001, 'timezone' => 'Africa/Luanda', 'runways' => 1, 'city' => 'Nzagi', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'CaluquembeAirport', 'iata' => '', 'latitude' => -13.775546, 'longitude' => 14.694916, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => '', 'country' => '']);
        DB::table('airports')->insert(['name' => 'Angola International (Under Construction)Airport', 'iata' => '', 'latitude' => -9.0484, 'longitude' => 13.5026, 'timezone' => 'Africa/Luanda', 'runways' => 0, 'city' => 'Luanda', 'country' => 'Angola (AO)']);
        DB::table('airports')->insert(['name' => 'Caleta Olivia Airport (CVI)', 'iata' => 'CVI', 'latitude' => -46.4318008, 'longitude' => -67.5186005, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 0, 'city' => 'Caleta Olivia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Charata Airport (CNT)', 'iata' => 'CNT', 'latitude' => -27.2164, 'longitude' => -61.2103, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Charata', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'General Villegas Airport (VGS)', 'iata' => 'VGS', 'latitude' => -35, 'longitude' => -63, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 2, 'city' => 'General Villegas', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Los Menucos Airport (LMD)', 'iata' => 'LMD', 'latitude' => -40.8176994, 'longitude' => -68.0746994, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Los Menucos', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Saenz Peña Airport (SZQ)', 'iata' => 'SZQ', 'latitude' => -26.8157997, 'longitude' => -60.4482994, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 0, 'city' => 'Presidencia Roque Sáenz Peña', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Valcheta Airport (VCF)', 'iata' => 'VCF', 'latitude' => -40.7000008, 'longitude' => -66.1500015, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Valcheta', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Carmen De Patagones Airport (CPG)', 'iata' => 'CPG', 'latitude' => -40.7781, 'longitude' => -62.9803, 'timezone' => 'America/Argentina/Salta', 'runways' => 2, 'city' => 'Carmen de Patagones', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Termal Airport (PRQ)', 'iata' => 'PRQ', 'latitude' => -26.7536106, 'longitude' => -60.4922218, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Presidencia Roque Sáenz Peña', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Loncopue Airport (LCP)', 'iata' => 'LCP', 'latitude' => -38.0819016, 'longitude' => -70.643898, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Loncopue', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Miramar Airport (MJR)', 'iata' => 'MJR', 'latitude' => -38.2271, 'longitude' => -57.8697, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 3, 'city' => 'Miramar', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Colonia Catriel Airport (CCT)', 'iata' => 'CCT', 'latitude' => -37.9101982, 'longitude' => -67.8349991, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Colonia Catriel', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Comodoro Pierrestegui Airport (COC)', 'iata' => 'COC', 'latitude' => -31.2969, 'longitude' => -57.9966, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Concordia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Gualeguaychu Airport (GHU)', 'iata' => 'GHU', 'latitude' => -33.0103, 'longitude' => -58.6131, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Gualeguaychu', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Junin Airport (JNI)', 'iata' => 'JNI', 'latitude' => -34.5459, 'longitude' => -60.9306, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Junin', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'General Urquiza Airport (PRA)', 'iata' => 'PRA', 'latitude' => -31.7948, 'longitude' => -60.4804, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Parana', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Islas Malvinas Airport (ROS)', 'iata' => 'ROS', 'latitude' => -32.9036, 'longitude' => -60.785, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Rosario', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Sauce Viejo Airport (SFN)', 'iata' => 'SFN', 'latitude' => -31.7117, 'longitude' => -60.8117, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Santa Fe', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Jorge Newbery Airpark Airport (AEP)', 'iata' => 'AEP', 'latitude' => -34.5592, 'longitude' => -58.4156, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Buenos Aires', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'La Cumbre Airport (LCM)', 'iata' => 'LCM', 'latitude' => -31.0058002, 'longitude' => -64.5318985, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'La Cumbre', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Ingeniero Ambrosio Taravella Airport (COR)', 'iata' => 'COR', 'latitude' => -31.3236008, 'longitude' => -64.2080002, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Cordoba', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'La Plata Airport (LPG)', 'iata' => 'LPG', 'latitude' => -34.9722, 'longitude' => -57.8947, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 2, 'city' => 'La Plata', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Ministro Pistarini International Airport (EZE)', 'iata' => 'EZE', 'latitude' => -34.8222, 'longitude' => -58.5358, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 2, 'city' => 'Buenos Aires', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Chos Malal Airport (HOS)', 'iata' => 'HOS', 'latitude' => -37.4446983, 'longitude' => -70.2225037, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Chos Malal', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Caviahue Airport (CVH)', 'iata' => 'CVH', 'latitude' => -37.8513985, 'longitude' => -71.009201, 'timezone' => 'America/Argentina/Salta', 'runways' => 0, 'city' => 'Lafontaine', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Dr. Arturo H. Illia Airport (GNR)', 'iata' => 'GNR', 'latitude' => -39.0007019, 'longitude' => -67.6204987, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'General Roca', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Rincon De Los Sauces Airport (RDS)', 'iata' => 'RDS', 'latitude' => -37.3905983, 'longitude' => -68.9041977, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Rincon de los Sauces', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Zapala Airport (APZ)', 'iata' => 'APZ', 'latitude' => -38.9754982, 'longitude' => -70.1136017, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Zapala', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'El Plumerillo Airport (MDZ)', 'iata' => 'MDZ', 'latitude' => -32.8316994, 'longitude' => -68.7929001, 'timezone' => 'America/Argentina/Mendoza', 'runways' => 1, 'city' => 'Mendoza', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Comodoro D.R. Salomón Airport (LGS)', 'iata' => 'LGS', 'latitude' => -35.4935989, 'longitude' => -69.5743027, 'timezone' => 'America/Argentina/Mendoza', 'runways' => 2, 'city' => 'Malargue', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Suboficial Ay Santiago Germano Airport (AFA)', 'iata' => 'AFA', 'latitude' => -34.5882988, 'longitude' => -68.4039001, 'timezone' => 'America/Argentina/Mendoza', 'runways' => 1, 'city' => 'San Rafael', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Catamarca Airport (CTC)', 'iata' => 'CTC', 'latitude' => -28.5956001, 'longitude' => -65.7517014, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 1, 'city' => 'Catamarca', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Vicecomodoro Angel D. La Paz Aragonés Airport (SDE)', 'iata' => 'SDE', 'latitude' => -27.7655563, 'longitude' => -64.3099976, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Santiago del Estero', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Las Termas Airport (RHD)', 'iata' => 'RHD', 'latitude' => -27.4736996, 'longitude' => -64.9055023, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 0, 'city' => 'Rio Hondo', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Capitan V A Almonacid Airport (IRJ)', 'iata' => 'IRJ', 'latitude' => -29.3815994, 'longitude' => -66.7957993, 'timezone' => 'America/Argentina/La_Rioja', 'runways' => 1, 'city' => 'La Rioja', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Teniente Benjamin Matienzo Airport (TUC)', 'iata' => 'TUC', 'latitude' => -26.8409004, 'longitude' => -65.1048965, 'timezone' => 'America/Argentina/Tucuman', 'runways' => 1, 'city' => 'San Miguel de Tucuman', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Domingo Faustino Sarmiento Airport (UAQ)', 'iata' => 'UAQ', 'latitude' => -31.5715008, 'longitude' => -68.4181976, 'timezone' => 'America/Argentina/San_Juan', 'runways' => 1, 'city' => 'San Juan', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Ceres Airport (CRR)', 'iata' => 'CRR', 'latitude' => -29.8631, 'longitude' => -61.8728, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Ceres', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Area De Material Airport (RCU)', 'iata' => 'RCU', 'latitude' => -33.0850983, 'longitude' => -64.2612991, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Rio Cuarto', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Villa Dolores Airport (VDR)', 'iata' => 'VDR', 'latitude' => -31.9452, 'longitude' => -65.1463013, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Villa Dolores', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Villa Reynolds Airport (VME)', 'iata' => 'VME', 'latitude' => -33.7299004, 'longitude' => -65.3873978, 'timezone' => 'America/Argentina/San_Luis', 'runways' => 2, 'city' => 'Villa Reynolds', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Brigadier Mayor D Cesar Raul Ojeda Airport (LUQ)', 'iata' => 'LUQ', 'latitude' => -33.273201, 'longitude' => -66.3563995, 'timezone' => 'America/Argentina/San_Luis', 'runways' => 1, 'city' => 'San Luis', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Corrientes Airport (CNQ)', 'iata' => 'CNQ', 'latitude' => -27.4455, 'longitude' => -58.7619, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Corrientes', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Resistencia International Airport (RES)', 'iata' => 'RES', 'latitude' => -27.45, 'longitude' => -59.0561, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Resistencia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Formosa Airport (FMA)', 'iata' => 'FMA', 'latitude' => -26.2127, 'longitude' => -58.2281, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Formosa', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Cataratas Del Iguazú International Airport (IGR)', 'iata' => 'IGR', 'latitude' => -25.7373009, 'longitude' => -54.4734001, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Puerto Iguazu', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Paso De Los Libres Airport (AOL)', 'iata' => 'AOL', 'latitude' => -29.6894, 'longitude' => -57.1521, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Paso de los Libres', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Monte Caseros Airport (MCS)', 'iata' => 'MCS', 'latitude' => -30.2719, 'longitude' => -57.6402, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Monte Caseros', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Libertador Gral D Jose De San Martin Airport (PSS)', 'iata' => 'PSS', 'latitude' => -27.3858, 'longitude' => -55.9707, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Posadas', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Martin Miguel De Guemes International Airport (SLA)', 'iata' => 'SLA', 'latitude' => -24.8560009, 'longitude' => -65.4861984, 'timezone' => 'America/Argentina/Salta', 'runways' => 2, 'city' => 'Salta', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Gobernador Horacio Guzman International Airport (JUJ)', 'iata' => 'JUJ', 'latitude' => -24.3927994, 'longitude' => -65.0978012, 'timezone' => 'America/Argentina/Jujuy', 'runways' => 1, 'city' => 'San Salvador de Jujuy', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Orán Airport (ORA)', 'iata' => 'ORA', 'latitude' => -23.1527996, 'longitude' => -64.3292007, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Orán', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'General Enrique Mosconi Airport (TTG)', 'iata' => 'TTG', 'latitude' => -22.6196003, 'longitude' => -63.7937012, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Tartagal', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Clorinda Airport (CLX)', 'iata' => 'CLX', 'latitude' => -25.3036, 'longitude' => -57.7344, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Clorinda', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'El Dorado Airport (ELO)', 'iata' => 'ELO', 'latitude' => -26.3974991, 'longitude' => -54.5746994, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'El Dorado', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Goya Airport (OYA)', 'iata' => 'OYA', 'latitude' => -29.1058, 'longitude' => -59.2189, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Goya', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Alferez Armando Rodriguez Airport (LLS)', 'iata' => 'LLS', 'latitude' => -24.7213993, 'longitude' => -60.5488014, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 0, 'city' => 'Las Lomitas', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Mercedes Airport (MDX)', 'iata' => 'MDX', 'latitude' => -29.2213993, 'longitude' => -58.0877991, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 0, 'city' => 'Mercedes', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Reconquista Airport (RCQ)', 'iata' => 'RCQ', 'latitude' => -29.2103, 'longitude' => -59.68, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 2, 'city' => 'Reconquista', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Curuzu Cuatia Airport (UZU)', 'iata' => 'UZU', 'latitude' => -29.7706, 'longitude' => -57.9789, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Curuzu Cuatia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'El Bolson Airport (EHL)', 'iata' => 'EHL', 'latitude' => -41.9431992, 'longitude' => -71.5323029, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'El Bolson', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'General E. Mosconi Airport (CRD)', 'iata' => 'CRD', 'latitude' => -45.7853, 'longitude' => -67.4655, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 1, 'city' => 'Comodoro Rivadavia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'El Maiten Airport (EMX)', 'iata' => 'EMX', 'latitude' => -42.0292015, 'longitude' => -71.1725006, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 3, 'city' => 'El Maiten', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Brigadier Antonio Parodi Airport (EQS)', 'iata' => 'EQS', 'latitude' => -42.9080009, 'longitude' => -71.1395035, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 2, 'city' => 'Esquel', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Las Heras Airport (LHS)', 'iata' => 'LHS', 'latitude' => -46.5382996, 'longitude' => -68.9653015, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 1, 'city' => 'Las Heras', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Cabo F.A.A. H. R. Bordón Airport (IGB)', 'iata' => 'IGB', 'latitude' => -41.3209, 'longitude' => -69.5748978, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Ingeniero Jacobacci', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Antoine De St Exupery Airport (OES)', 'iata' => 'OES', 'latitude' => -40.7512, 'longitude' => -65.0343, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'San Antonio Oeste', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Maquinchao Airport (MQD)', 'iata' => 'MQD', 'latitude' => -41.2430992, 'longitude' => -68.7078018, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Maquinchao', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'D. Casimiro Szlapelis Airport (ARR)', 'iata' => 'ARR', 'latitude' => -45.0135994, 'longitude' => -70.8122025, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 1, 'city' => 'Alto Rio Senguerr', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Sierra Grande Airport (SGV)', 'iata' => 'SGV', 'latitude' => -41.5917015, 'longitude' => -65.3394012, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Sierra Grande', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Almirante Marco Andres Zar Airport (REL)', 'iata' => 'REL', 'latitude' => -43.2105, 'longitude' => -65.2703, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 1, 'city' => 'Rawson', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Gobernador Castello Airport (VDM)', 'iata' => 'VDM', 'latitude' => -40.8692, 'longitude' => -63.0004, 'timezone' => 'America/Argentina/Salta', 'runways' => 2, 'city' => 'Viedma / Carmen de Patagones', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'El Tehuelche Airport (PMY)', 'iata' => 'PMY', 'latitude' => -42.7592, 'longitude' => -65.1027, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 1, 'city' => 'Puerto Madryn', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Lago Argentino Airport (ING)', 'iata' => 'ING', 'latitude' => -50.3361015, 'longitude' => -72.2485962, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 0, 'city' => 'El Calafate', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'El Calafate Airport (FTE)', 'iata' => 'FTE', 'latitude' => -50.2803001, 'longitude' => -72.0531006, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 1, 'city' => 'El Calafate', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Puerto Deseado Airport (PUD)', 'iata' => 'PUD', 'latitude' => -47.7353, 'longitude' => -65.9041, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 1, 'city' => 'Puerto Deseado', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Hermes Quijada International Airport (RGA)', 'iata' => 'RGA', 'latitude' => -53.7777, 'longitude' => -67.7494, 'timezone' => 'America/Argentina/Ushuaia', 'runways' => 1, 'city' => 'Rio Grande', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Piloto Civil N. Fernández Airport (RGL)', 'iata' => 'RGL', 'latitude' => -51.6089, 'longitude' => -69.3126, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 1, 'city' => 'Rio Gallegos', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Malvinas Argentinas Airport (USH)', 'iata' => 'USH', 'latitude' => -54.8433, 'longitude' => -68.2958, 'timezone' => 'America/Argentina/Ushuaia', 'runways' => 1, 'city' => 'Ushuahia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Capitan D Daniel Vazquez Airport (ULA)', 'iata' => 'ULA', 'latitude' => -49.3068, 'longitude' => -67.8026, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 1, 'city' => 'San Julian', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Rio Mayo Airport (ROY)', 'iata' => 'ROY', 'latitude' => -45.7038994, 'longitude' => -70.2455978, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 1, 'city' => 'Rio Mayo', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Perito Moreno Airport (PMQ)', 'iata' => 'PMQ', 'latitude' => -46.537899, 'longitude' => -70.9786987, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 3, 'city' => 'Perito Moreno', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Gobernador Gregores Airport (GGS)', 'iata' => 'GGS', 'latitude' => -48.7831001, 'longitude' => -70.1500015, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 1, 'city' => 'Gobernador Gregores', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Jose De San Martin Airport (JSM)', 'iata' => 'JSM', 'latitude' => -44.0485992, 'longitude' => -70.4589005, 'timezone' => 'America/Argentina/Catamarca', 'runways' => 2, 'city' => 'Chubut', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => '28 De Noviembre Airport (RYO)', 'iata' => 'RYO', 'latitude' => -51.6091995, 'longitude' => -72.2217026, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 3, 'city' => 'El Turbio', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Santa Cruz Airport (RZA)', 'iata' => 'RZA', 'latitude' => -50.0165, 'longitude' => -68.5792, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 5, 'city' => 'Santa Cruz', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Comandante Espora Airport (BHI)', 'iata' => 'BHI', 'latitude' => -38.725, 'longitude' => -62.1693, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 3, 'city' => 'Bahia Blanca', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Brigadier D.H.E. Ruiz Airport (CSZ)', 'iata' => 'CSZ', 'latitude' => -37.4460983, 'longitude' => -61.8893013, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Coronel Suarez', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Olavarria Airport (OVR)', 'iata' => 'OVR', 'latitude' => -36.8899994, 'longitude' => -60.2165985, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 2, 'city' => 'Olavarria', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'General Pico Airport (GPO)', 'iata' => 'GPO', 'latitude' => -35.6962013, 'longitude' => -63.7583008, 'timezone' => 'America/Argentina/Salta', 'runways' => 2, 'city' => 'General Pico', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Tres Arroyos Airport (OYO)', 'iata' => 'OYO', 'latitude' => -38.3869, 'longitude' => -60.3297, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 3, 'city' => 'Tres Arroyos', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Santa Teresita Airport (SST)', 'iata' => 'SST', 'latitude' => -36.5423, 'longitude' => -56.7218, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Santa Teresita', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Ástor Piazzola International Airport (MDQ)', 'iata' => 'MDQ', 'latitude' => -37.9342, 'longitude' => -57.5733, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Mar del Plata', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Presidente Peron Airport (NQN)', 'iata' => 'NQN', 'latitude' => -38.9490013, 'longitude' => -68.1557007, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Neuquen', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Necochea Airport (NEC)', 'iata' => 'NEC', 'latitude' => -38.4831, 'longitude' => -58.8172, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 3, 'city' => 'Necochea', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Comodoro Pedro Zanni Airport (PEH)', 'iata' => 'PEH', 'latitude' => -35.8446, 'longitude' => -61.8576, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Pehuajó', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Santa Rosa Airport (RSA)', 'iata' => 'RSA', 'latitude' => -36.5882988, 'longitude' => -64.2757034, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Santa Rosa', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'San Carlos De Bariloche Airport (BRC)', 'iata' => 'BRC', 'latitude' => -41.1511993, 'longitude' => -71.1575012, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'San Carlos de Bariloche', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Héroes De Malvinas Airport (TDL)', 'iata' => 'TDL', 'latitude' => -37.2374001, 'longitude' => -59.2279015, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Tandil', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Villa Gesell Airport (VLG)', 'iata' => 'VLG', 'latitude' => -37.2354, 'longitude' => -57.0292, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Villa Gesell', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Cutral-Co Airport (CUT)', 'iata' => 'CUT', 'latitude' => -38.9397011, 'longitude' => -69.2646027, 'timezone' => 'America/Argentina/Salta', 'runways' => 2, 'city' => 'Cutral-Co', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Aviador C. Campos Airport (CPC)', 'iata' => 'CPC', 'latitude' => -40.0754013, 'longitude' => -71.1372986, 'timezone' => 'America/Argentina/Salta', 'runways' => 1, 'city' => 'Chapelco/San Martin de los Andes', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Colonia Sarmiento Airport (OLN)', 'iata' => 'OLN', 'latitude' => -45.5833333, 'longitude' => -69, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 0, 'city' => 'Colonia Sarmiento', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'CullenAirport', 'iata' => '', 'latitude' => -52.8851013, 'longitude' => -68.4122009, 'timezone' => 'America/Argentina/Ushuaia', 'runways' => 0, 'city' => 'Cullen', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Los CerrosAirport', 'iata' => '', 'latitude' => -54.344101, 'longitude' => -67.832901, 'timezone' => 'America/Argentina/Ushuaia', 'runways' => 0, 'city' => 'Los Cerros', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Rio BellavistaAirport', 'iata' => '', 'latitude' => -53.9827003, 'longitude' => -68.5235977, 'timezone' => 'America/Argentina/Ushuaia', 'runways' => 0, 'city' => 'Rio Bellavista', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'MerloAirport', 'iata' => '', 'latitude' => -32.3582001, 'longitude' => -65.0174026, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 0, 'city' => 'Merlo', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Bragado Airport (QRF)', 'iata' => 'QRF', 'latitude' => -35.144, 'longitude' => -60.4803, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 2, 'city' => 'Bragado', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Aeroclub ChacoAirport', 'iata' => '', 'latitude' => -27.6311, 'longitude' => -59.1797, 'timezone' => 'America/Asuncion', 'runways' => 1, 'city' => 'Resistencia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Aerofumigaciones Don AlejandroAirport', 'iata' => '', 'latitude' => -33.3053, 'longitude' => -60.6539, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Coronel Bogado', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Agro Servicio YorisAirport', 'iata' => '', 'latitude' => -26.5830555, 'longitude' => -64.5297241, 'timezone' => 'America/Argentina/Tucuman', 'runways' => 1, 'city' => 'Gobernador Garmendia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'AgroaireAirport', 'iata' => '', 'latitude' => -27.4978, 'longitude' => -61.6586, 'timezone' => 'America/Argentina/Tucuman', 'runways' => 1, 'city' => 'Gancedo', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Antoine De Saint ExuperyAirport', 'iata' => '', 'latitude' => -40.7401009, 'longitude' => -64.9804993, 'timezone' => 'America/Argentina/San_Luis', 'runways' => 0, 'city' => 'San Antonio Oeste', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => '13 De DiciembreAirport', 'iata' => '', 'latitude' => -45.9033, 'longitude' => -67.5564, 'timezone' => 'America/Argentina/Rio_Gallegos', 'runways' => 2, 'city' => 'Comodoro Rivadavia', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'Abel MonteverdeAirport', 'iata' => '', 'latitude' => -32.9208, 'longitude' => -62.4663, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Monte Buey', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'AcindarAirport', 'iata' => '', 'latitude' => -33.2647, 'longitude' => -60.2842, 'timezone' => 'America/Argentina/Buenos_Aires', 'runways' => 1, 'city' => 'Villa Constitución', 'country' => 'Argentina (AR)']);
        DB::table('airports')->insert(['name' => 'AeroboeroAirport', 'iata' => '', 'latitude' => -30.7286, 'longitude' => -62.0078, 'timezone' => 'America/Argentina/Cordoba', 'runways' => 1, 'city' => 'Morteros', 'country' => 'Argentina (AR)']);
    }
}
